/************************************************************************************
 *  File name: mumessage.h
 *  Modified: 22 November 2017
 *  Author:  Christopher Crary
 *  Purpose: Header file for MuMessage, a built-in messaging application for MuPhone.
************************************************************************************/

/////////////////////////////////DEPENDENCIES////////////////////////////////////////
/////////////////////////////END OF DEPENDENCIES/////////////////////////////////////

////////////////////////////////////DEFINES//////////////////////////////////////////

//header guard
#ifndef MUMESSAGE_H_
#define MUMESSAGE_H_

/* boundaries for LCD screen */
#define LCD_SCREEN_X_MIN 0
#define LCD_SCREEN_X_MAX 320
#define LCD_SCREEN_Y_MIN 0
#define LCD_SCREEN_Y_MAX 240

/* LCD text */
#define LCD_TEXT_WIDTH      8       // in terms of pixels
#define LCD_TEXT_HEIGHT     16
#define LCD_TEXT_COLOR      LCD_BLACK

/* text cursor defines */
#define CURSOR_WIDTH        2       // in terms of pixels
#define CURSOR_HEIGHT       16
#define CURSOR_COLOR        LCD_BLACK

/************************** COMPOSE MESSAGE DEFINES ********************************/

/* defined color palette */
#define COMPOSE_MESSAGE_BACKGROUND_COLOR            LCD_WHITE
#define COMPOSE_MESSAGE_HEADER_COLOR                LCD_LIGHT_GRAY
#define COMPOSE_MESSAGE_HEADER_DIVIDER_COLOR        LCD_BLACK
#define COMPOSE_MESSAGE_BACK_BUTTON_COLOR           LCD_LIGHT_GRAY
#define COMPOSE_MESSAGE_BACK_BUTTON_TEXT_COLOR      LCD_BLACK
#define COMPOSE_MESSAGE_SEND_BUTTON_COLOR           LCD_LIGHT_GRAY
#define COMPOSE_MESSAGE_SEND_BUTTON_TEXT_COLOR      LCD_BLACK
#define COMPOSE_MESSAGE_TEXT_ARENA_COLOR            LCD_WHITE
#define KEYBOARD_DIVIDER_COLOR                      LCD_DARK_GRAY
#define KEYBOARD_COLOR                              LCD_DARK_GRAY
#define KEYBOARD_KEY_NO_CLICK_COLOR                 LCD_LIGHT_GRAY
#define KEYBOARD_KEY_TEXT_NO_CLICK_COLOR            LCD_BLACK
#define KEYBOARD_KEY_CLICK_COLOR                    LCD_DARK_BLUE
#define KEYBOARD_KEY_TEXT_CLICK_COLOR               LCD_WHITE

/* boundaries of compose message background */
#define COMPOSE_MESSAGE_BACKGROUND_X_MIN            LCD_SCREEN_X_MIN
#define COMPOSE_MESSAGE_BACKGROUND_X_MAX            LCD_SCREEN_X_MAX
#define COMPOSE_MESSAGE_BACKGROUND_Y_MIN            LCD_SCREEN_Y_MIN
#define COMPOSE_MESSAGE_BACKGROUND_Y_MAX            LCD_SCREEN_Y_MAX

/* boundaries of compose message header */
#define COMPOSE_MESSAGE_HEADER_WIDTH            (LCD_SCREEN_X_MAX - LCD_SCREEN_X_MIN)
#define COMPOSE_MESSAGE_HEADER_HEIGHT           20
#define COMPOSE_MESSAGE_HEADER_X_MIN            LCD_SCREEN_X_MIN
#define COMPOSE_MESSAGE_HEADER_X_MAX            (LCD_SCREEN_X_MIN + COMPOSE_MESSAGE_HEADER_WIDTH)
#define COMPOSE_MESSAGE_HEADER_Y_MIN            LCD_SCREEN_Y_MIN
#define COMPOSE_MESSAGE_HEADER_Y_MAX            (COMPOSE_MESSAGE_HEADER_Y_MIN + COMPOSE_MESSAGE_HEADER_HEIGHT)

#define COMPOSE_MESSAGE_HEADER_DIVIDER_WIDTH        (COMPOSE_MESSAGE_HEADER_X_MAX - COMPOSE_MESSAGE_HEADER_X_MIN)
#define COMPOSE_MESSAGE_HEADER_DIVIDER_HEIGHT       1
#define COMPOSE_MESSAGE_HEADER_DIVIDER_X_MIN        COMPOSE_MESSAGE_HEADER_X_MIN
#define COMPOSE_MESSAGE_HEADER_DIVIDER_X_MAX        (COMPOSE_MESSAGE_HEADER_DIVIDER_X_MIN + COMPOSE_MESSAGE_HEADER_DIVIDER_WIDTH)
#define COMPOSE_MESSAGE_HEADER_DIVIDER_Y_MIN        COMPOSE_MESSAGE_HEADER_Y_MAX
#define COMPOSE_MESSAGE_HEADER_DIVIDER_Y_MAX        (COMPOSE_MESSAGE_HEADER_DIVIDER_Y_MIN + COMPOSE_MESSAGE_HEADER_DIVIDER_HEIGHT)

#define COMPOSE_MESSAGE_BACK_BUTTON_OFFSET      2       // spacing used for edges of button
#define COMPOSE_MESSAGE_BACK_BUTTON_X_MIN       ((LCD_TEXT_WIDTH * 0) + (COMPOSE_MESSAGE_BACK_BUTTON_OFFSET * 1))
#define COMPOSE_MESSAGE_BACK_BUTTON_X_MAX       ((LCD_TEXT_WIDTH * 6) + (COMPOSE_MESSAGE_BACK_BUTTON_OFFSET * 2))
#define COMPOSE_MESSAGE_BACK_BUTTON_Y_MIN       LCD_SCREEN_Y_MIN
#define COMPOSE_MESSAGE_BACK_BUTTON_Y_MAX       (COMPOSE_MESSAGE_BACK_BUTTON_Y_MIN + LCD_TEXT_HEIGHT + COMPOSE_MESSAGE_BACK_BUTTON_OFFSET)

#define COMPOSE_MESSAGE_SEND_BUTTON_OFFSET      2       // spacing used for edges of button
#define COMPOSE_MESSAGE_SEND_BUTTON_X_MIN       (LCD_SCREEN_X_MAX - (LCD_TEXT_WIDTH * 12) - (COMPOSE_MESSAGE_SEND_BUTTON_OFFSET * 1))
#define COMPOSE_MESSAGE_SEND_BUTTON_X_MAX       LCD_SCREEN_X_MAX
#define COMPOSE_MESSAGE_SEND_BUTTON_Y_MIN       LCD_SCREEN_Y_MIN
#define COMPOSE_MESSAGE_SEND_BUTTON_Y_MAX       (COMPOSE_MESSAGE_SEND_BUTTON_Y_MIN + LCD_TEXT_HEIGHT + COMPOSE_MESSAGE_SEND_BUTTON_OFFSET)

#define COMPOSE_MESSAGE_BACK_BUTTON_TEXT_X_OFFSET       0
#define COMPOSE_MESSAGE_BACK_BUTTON_TEXT_Y_OFFSET       2
#define COMPOSE_MESSAGE_BACK_BUTTON_TEXT_X_START        (COMPOSE_MESSAGE_BACK_BUTTON_X_MIN + COMPOSE_MESSAGE_BACK_BUTTON_TEXT_X_OFFSET)
#define COMPOSE_MESSAGE_BACK_BUTTON_TEXT_Y_START        (COMPOSE_MESSAGE_BACK_BUTTON_Y_MIN + COMPOSE_MESSAGE_BACK_BUTTON_TEXT_Y_OFFSET)

#define COMPOSE_MESSAGE_SEND_BUTTON_TEXT_X_OFFSET       0
#define COMPOSE_MESSAGE_SEND_BUTTON_TEXT_Y_OFFSET       2
#define COMPOSE_MESSAGE_SEND_BUTTON_TEXT_X_START        (COMPOSE_MESSAGE_SEND_BUTTON_X_MIN + COMPOSE_MESSAGE_SEND_BUTTON_TEXT_X_OFFSET)
#define COMPOSE_MESSAGE_SEND_BUTTON_TEXT_Y_START        (COMPOSE_MESSAGE_SEND_BUTTON_Y_MIN + COMPOSE_MESSAGE_SEND_BUTTON_TEXT_Y_OFFSET)

/* boundaries of text arena */
#define TEXT_ARENA_WIDTH        (LCD_SCREEN_X_MAX - LCD_SCREEN_X_MIN)
#define TEXT_ARENA_HEIGHT       46
#define TEXT_ARENA_X_MIN        LCD_SCREEN_X_MIN
#define TEXT_ARENA_X_MAX        (TEXT_ARENA_X_MIN + TEXT_ARENA_WIDTH)
#define TEXT_ARENA_Y_MIN        (COMPOSE_MESSAGE_BACKGROUND_Y_MIN + COMPOSE_MESSAGE_HEADER_HEIGHT + COMPOSE_MESSAGE_HEADER_DIVIDER_HEIGHT)
#define TEXT_ARENA_Y_MAX        (TEXT_ARENA_Y_MIN + TEXT_ARENA_HEIGHT)


/* boundaries of keyboard */

#define KEYBOARD_DIVIDER_WIDTH  (LCD_SCREEN_X_MAX - LCD_SCREEN_X_MIN)
#define KEYBOARD_DIVIDER_HEIGHT 1
#define KEYBOARD_DIVIDER_X_MIN  LCD_SCREEN_X_MIN
#define KEYBOARD_DIVIDER_X_MAX  KEYBOARD_DIVIDER_X_MIN + KEYBOARD_DIVIDER_WIDTH
#define KEYBOARD_DIVIDER_Y_MIN  (COMPOSE_MESSAGE_BACKGROUND_Y_MIN + (COMPOSE_MESSAGE_HEADER_HEIGHT + COMPOSE_MESSAGE_HEADER_DIVIDER_HEIGHT + TEXT_ARENA_HEIGHT))
#define KEYBOARD_DIVIDER_Y_MAX  (KEYBOARD_DIVIDER_Y_MIN + KEYBOARD_DIVIDER_HEIGHT)

#define KEYBOARD_WIDTH          (LCD_SCREEN_X_MAX - LCD_SCREEN_X_MIN)
#define KEYBOARD_HEIGHT         172
#define KEYBOARD_X_MIN          LCD_SCREEN_X_MIN
#define KEYBOARD_X_MAX          (KEYBOARD_X_MIN + KEYBOARD_WIDTH)
#define KEYBOARD_Y_MIN          (COMPOSE_MESSAGE_BACKGROUND_Y_MIN + (COMPOSE_MESSAGE_HEADER_HEIGHT + COMPOSE_MESSAGE_HEADER_DIVIDER_HEIGHT + TEXT_ARENA_HEIGHT + KEYBOARD_DIVIDER_HEIGHT))
#define KEYBOARD_Y_MAX          (KEYBOARD_Y_MIN + KEYBOARD_HEIGHT)



/* boundaries for keyboard buttons */

#define KEYBOARD_X_ROW1_EDGE_OFFSET         (KEYBOARD_X_MIN + 4)       // edge spacing for row 1 of 4 on keyboard
#define KEYBOARD_X_ROW2_EDGE_OFFSET         (KEYBOARD_X_MIN + 18)       // edge spacing for row 2 of 4 on keyboard
#define KEYBOARD_X_ROW3_EDGE_OFFSET         (KEYBOARD_X_MIN + 4)       // edge spacing for row 3 of 4 on keyboard
#define KEYBOARD_X_ROW4_EDGE_OFFSET         (KEYBOARD_X_MIN + 6)       // edge spacing for row 4 of 4 on keyboard
#define KEYBOARD_Y_EDGE_OFFSET              (KEYBOARD_Y_MIN + 4)       // constant edge spacing for top and bottom of keyboard

#define KEYBOARD_BUTTON_WIDTH_OFFSET     6          // spacing between each key
#define KEYBOARD_BUTTON_HEIGHT_OFFSET    4
#define KEYBOARD_BUTTON_WIDTH           26          // size of each keyboard key
#define KEYBOARD_BUTTON_HEIGHT          38

#define KEYBOARD_BUTTON_BIG_WIDTH_OFFSET       9        // spacing and size for big buttons (row 3 of keyboard)
#define KEYBOARD_BUTTON_BIG_WIDTH              36
#define KEYBOARD_BUTTON_BIG_HEIGHT             38

#define KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET    6        // spacing and size for bigger buttons (row 4 of keyboard)
#define KEYBOARD_BUTTON_BIGGER_WIDTH           75
#define KEYBOARD_BUTTON_BIGGER_HEIGHT          38

#define KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET    6        // spacing and size for biggest buttons (row 4 of keyboard)
#define KEYBOARD_BUTTON_BIGGEST_WIDTH           150
#define KEYBOARD_BUTTON_BIGGEST_HEIGHT          38

/* boundaries for keyboard button text */
#define KEYBOARD_BUTTON_TEXT_X_OFFSET       ((KEYBOARD_BUTTON_WIDTH - LCD_TEXT_WIDTH) >> 1)
#define KEYBOARD_BUTTON_TEXT_Y_OFFSET       ((KEYBOARD_BUTTON_HEIGHT - LCD_TEXT_HEIGHT) >> 1)
#define KEYBOARD_BUTTON_BIG_TEXT_X_OFFSET   ((KEYBOARD_BUTTON_BIG_WIDTH - LCD_TEXT_WIDTH) >> 1)
#define KEYBOARD_BUTTON_BIG_TEXT_Y_OFFSET   ((KEYBOARD_BUTTON_BIG_HEIGHT - LCD_TEXT_HEIGHT) >> 1)
#define KEYBOARD_BUTTON_BIGGER_TEXT_X_OFFSET   ((KEYBOARD_BUTTON_BIGGER_WIDTH - (LCD_TEXT_WIDTH) >> 1)
#define KEYBOARD_BUTTON_BIGGER_TEXT_Y_OFFSET   ((KEYBOARD_BUTTON_BIGGER_HEIGHT - LCD_TEXT_HEIGHT) >> 1)
#define KEYBOARD_BUTTON_BIGGEST_TEXT_X_OFFSET   ((KEYBOARD_BUTTON_BIGGEST_WIDTH - LCD_TEXT_WIDTH) >> 1)
#define KEYBOARD_BUTTON_BIGGEST_TEXT_Y_OFFSET   ((KEYBOARD_BUTTON_BIGGEST_HEIGHT - LCD_TEXT_HEIGHT) >> 1)

// keyboard #1 (lower-case keyboard)

/* row 1 (of 4) keys on keyboard */
#define Q_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 0) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define Q_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define Q_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define Q_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define Q_BUTTON_TEXT_X_START       (Q_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define Q_BUTTON_TEXT_Y_START       (Q_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define W_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define W_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define W_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define W_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define W_BUTTON_TEXT_X_START       (W_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define W_BUTTON_TEXT_Y_START       (W_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define E_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define E_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define E_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define E_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define E_BUTTON_TEXT_X_START       (E_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define E_BUTTON_TEXT_Y_START       (E_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define R_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define R_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define R_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define R_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define R_BUTTON_TEXT_X_START       (R_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define R_BUTTON_TEXT_Y_START       (R_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define T_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define T_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define T_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define T_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define T_BUTTON_TEXT_X_START       (T_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define T_BUTTON_TEXT_Y_START       (T_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define Y_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define Y_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define Y_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define Y_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define Y_BUTTON_TEXT_X_START       (Y_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define Y_BUTTON_TEXT_Y_START       (Y_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define U_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define U_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define U_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define U_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define U_BUTTON_TEXT_X_START       (U_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define U_BUTTON_TEXT_Y_START       (U_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define I_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 7))
#define I_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 8) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 7))
#define I_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define I_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define I_BUTTON_TEXT_X_START       (I_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define I_BUTTON_TEXT_Y_START       (I_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define O_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 8) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 8))
#define O_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 9) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 8))
#define O_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define O_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define O_BUTTON_TEXT_X_START       (O_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define O_BUTTON_TEXT_Y_START       (O_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define P_BUTTON_X_MIN    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 9) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 9))
#define P_BUTTON_X_MAX    (KEYBOARD_X_ROW1_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 10) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 9))
#define P_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 0) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))
#define P_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 0))

#define P_BUTTON_TEXT_X_START       (P_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define P_BUTTON_TEXT_Y_START       (P_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

/* row 2 (of 4) keys on keyboard */
#define A_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 0) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define A_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define A_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define A_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define A_BUTTON_TEXT_X_START       (A_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define A_BUTTON_TEXT_Y_START       (A_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define S_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define S_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define S_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define S_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define S_BUTTON_TEXT_X_START       (S_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define S_BUTTON_TEXT_Y_START       (S_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define D_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define D_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define D_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define D_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define D_BUTTON_TEXT_X_START       (D_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define D_BUTTON_TEXT_Y_START       (D_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define F_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define F_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define F_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define F_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define F_BUTTON_TEXT_X_START       (F_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define F_BUTTON_TEXT_Y_START       (F_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define G_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define G_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define G_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define G_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define G_BUTTON_TEXT_X_START       (G_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define G_BUTTON_TEXT_Y_START       (G_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define H_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define H_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define H_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define H_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define H_BUTTON_TEXT_X_START       (H_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define H_BUTTON_TEXT_Y_START       (H_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define J_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define J_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define J_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define J_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define J_BUTTON_TEXT_X_START       (J_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define J_BUTTON_TEXT_Y_START       (J_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define K_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 7))
#define K_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 8) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 7))
#define K_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define K_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define K_BUTTON_TEXT_X_START       (K_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define K_BUTTON_TEXT_Y_START       (K_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define L_BUTTON_X_MIN    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 8) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 8))
#define L_BUTTON_X_MAX    (KEYBOARD_X_ROW2_EDGE_OFFSET + (KEYBOARD_BUTTON_WIDTH * 9) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 8))
#define L_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 1) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))
#define L_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 1))

#define L_BUTTON_TEXT_X_START       (L_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define L_BUTTON_TEXT_Y_START       (L_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

/* row 3 (of 4) keys on keyboard */

// button to change keyboard to upper-case keyboard (keyboard #2)
#define UPPERCASE_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 0) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 0) + (KEYBOARD_BUTTON_WIDTH * 0) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define UPPERCASE_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 0) + (KEYBOARD_BUTTON_WIDTH * 0) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define UPPERCASE_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define UPPERCASE_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define UPPERCASE_BUTTON_TEXT_X_START       (UPPERCASE_BUTTON_X_MIN + KEYBOARD_BUTTON_BIG_TEXT_X_OFFSET)
#define UPPERCASE_BUTTON_TEXT_Y_START       (UPPERCASE_BUTTON_Y_MIN + KEYBOARD_BUTTON_BIG_TEXT_Y_OFFSET)

#define Z_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 0) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define Z_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 0))
#define Z_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define Z_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define Z_BUTTON_TEXT_X_START       (Z_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define Z_BUTTON_TEXT_Y_START       (Z_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define X_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 1) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define X_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 1))
#define X_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define X_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define X_BUTTON_TEXT_X_START       (X_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define X_BUTTON_TEXT_Y_START       (X_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define C_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 2) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define C_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 2))
#define C_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define C_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define C_BUTTON_TEXT_X_START       (C_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define C_BUTTON_TEXT_Y_START       (C_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define V_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 3) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define V_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 3))
#define V_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define V_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define V_BUTTON_TEXT_X_START       (V_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define V_BUTTON_TEXT_Y_START       (V_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define B_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 4) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define B_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 4))
#define B_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define B_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define B_BUTTON_TEXT_X_START       (B_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define B_BUTTON_TEXT_Y_START       (B_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define N_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 5) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define N_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 5))
#define N_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define N_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define N_BUTTON_TEXT_X_START       (N_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define N_BUTTON_TEXT_Y_START       (N_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

#define M_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 6) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define M_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define M_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define M_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define M_BUTTON_TEXT_X_START       (M_BUTTON_X_MIN + KEYBOARD_BUTTON_TEXT_X_OFFSET)
#define M_BUTTON_TEXT_Y_START       (M_BUTTON_Y_MIN + KEYBOARD_BUTTON_TEXT_Y_OFFSET)

// button to remove last-typed character from text
#define BACKSPACE_BUTTON_X_MIN    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 1) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 2) + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 6))
#define BACKSPACE_BUTTON_X_MAX    (KEYBOARD_X_ROW3_EDGE_OFFSET + (KEYBOARD_BUTTON_BIG_WIDTH * 2) + (KEYBOARD_BUTTON_BIG_WIDTH_OFFSET * 2) + (KEYBOARD_BUTTON_WIDTH * 7) + (KEYBOARD_BUTTON_WIDTH_OFFSET * 7))
#define BACKSPACE_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 2) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))
#define BACKSPACE_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 2))

#define BACKSPACE_BUTTON_TEXT_X_START       (BACKSPACE_BUTTON_X_MIN + KEYBOARD_BUTTON_BIG_TEXT_X_OFFSET)
#define BACKSPACE_BUTTON_TEXT_Y_START       (BACKSPACE_BUTTON_Y_MIN + KEYBOARD_BUTTON_BIG_TEXT_Y_OFFSET)

/* row 4 (of 4) keys on keyboard */

// button to change keyboard to numbers keyboard (keyboard #3)
#define NUMBERS_BUTTON_X_MIN    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 0) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 0) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 0) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 0))
#define NUMBERS_BUTTON_X_MAX    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 0) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 0) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 0))
#define NUMBERS_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))
#define NUMBERS_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 4) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))

#define NUMBERS_BUTTON_TEXT_X_START       (NUMBERS_BUTTON_X_MIN + ((KEYBOARD_BUTTON_BIGGER_WIDTH - (LCD_TEXT_WIDTH * 3)) >> 1))
#define NUMBERS_BUTTON_TEXT_Y_START       (NUMBERS_BUTTON_Y_MIN + KEYBOARD_BUTTON_BIGGER_TEXT_Y_OFFSET)

#define SPACE_BUTTON_X_MIN    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 0) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 0))
#define SPACE_BUTTON_X_MAX    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 0))
#define SPACE_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))
#define SPACE_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 4) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))

#define SPACE_BUTTON_TEXT_X_START       (SPACE_BUTTON_X_MIN + ((KEYBOARD_BUTTON_BIGGEST_WIDTH - (LCD_TEXT_WIDTH * 5)) >> 1))
#define SPACE_BUTTON_TEXT_Y_START       (SPACE_BUTTON_Y_MIN + KEYBOARD_BUTTON_BIGGEST_TEXT_Y_OFFSET)

#define RETURN_BUTTON_X_MIN    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 1))
#define RETURN_BUTTON_X_MAX    (KEYBOARD_X_ROW4_EDGE_OFFSET + (KEYBOARD_BUTTON_BIGGER_WIDTH * 2) + (KEYBOARD_BUTTON_BIGGER_WIDTH_OFFSET * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH * 1) + (KEYBOARD_BUTTON_BIGGEST_WIDTH_OFFSET * 1))
#define RETURN_BUTTON_Y_MIN    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 3) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))
#define RETURN_BUTTON_Y_MAX    (KEYBOARD_Y_EDGE_OFFSET + (KEYBOARD_BUTTON_HEIGHT * 4) + (KEYBOARD_BUTTON_HEIGHT_OFFSET * 3))

#define RETURN_BUTTON_TEXT_X_START       (RETURN_BUTTON_X_MIN + ((KEYBOARD_BUTTON_BIGGER_WIDTH - (LCD_TEXT_WIDTH * 6)) >> 1))
#define RETURN_BUTTON_TEXT_Y_START       (RETURN_BUTTON_Y_MIN + KEYBOARD_BUTTON_BIGGER_TEXT_Y_OFFSET)

// keyboard #2 (upper-case keyboard)


/************************* END OF COMPOSE MESSAGE DEFINES **************************/



////////////////////////////////END OF DEFINES///////////////////////////////////////

////////////////////////////////////EXTERNS//////////////////////////////////////////
////////////////////////////////END OF EXTERNS///////////////////////////////////////

//////////////////////////////PUBLIC DATA MEMBERS////////////////////////////////////
//////////////////////////END OF PUBLIC DATA MEMBERS/////////////////////////////////

//////////////////////////////PRIVATE DATA MEMBERS///////////////////////////////////
//////////////////////////END OF PRIVATE DATA MEMBERS////////////////////////////////

////////////////////////////////INLINE FUNCTIONS/////////////////////////////////////
////////////////////////////END OF INLINE FUNCTIONS//////////////////////////////////

////////////////////////////PUBLIC FUNCTION PROTOTYPES///////////////////////////////

/************************************************************************************
* Name: app_init()
* Purpose: Static helper function to initialize the MuMessage application, within
*          the thread_mumessage_start_application
* Input(s):
* Output:
************************************************************************************/
static inline void app_init(void);

//////////////////////////END OF PUBLIC FUNCTION PROTOTYPES//////////////////////////

////////////////////////////////////THREADS//////////////////////////////////////////

/****************************** APERIODIC THREADS **********************************/

/************************************************************************************
 * Name: aperiodic_mumessage_compose_message
 * Purpose: Aperiodic event created after the initial display of the Compose Message
 *          screen within MuMessage. If a valid touch was made to the LCD TouchPanel,
 *          a thread for checking what section of the screen was pressed will be
 *          created.
 * Input(s): N/A
 * Output: N/A
 ***********************************************************************************/
void aperiodic_mumessage_compose_message(void);

/************************** END OF APERIODIC THREADS *******************************/


/******************************* COMMON THREADS ************************************/

/* threads for Compose Message */

/************************************************************************************
* Name: thread_mumessage_compose_message
* Purpose: Thread to draw Compose Message screen, and prepare for sending a
*          message to another MuPhone user.
* Input(s): N/A
* Output: N/A
************************************************************************************/
void thread_mumessage_compose_message(void);

/************************************************************************************
* Name: thread_mumessage_compose_message_check_TP
* Purpose: Thread to check if touch made to LCD TouchPanel interacted with any
*          predefined sections in the Compose Message screen of MuMessage.
* Input(s): N/A
* Output: N/A
************************************************************************************/
void thread_mumessage_compose_message_check_TP(void);


/************************************************************************************
* Name: thread_mumessage_check_for_messages
* Purpose: Background thread to check if new messages were received
* Input(s): N/A
* Output: N/A
************************************************************************************/
void thread_mumessage_check_for_messages(void);

/************************************************************************************
* Name: thread_mumessage_open_app
* Purpose: Thread to open already initialized MuMessage application instance
* Input(s): N/A
* Output: N/A
************************************************************************************/
void thread_mumessage_open_app(void);

/************************************************************************************
* Name: thread_mumessage_start_app
* Purpose: Thread to initialize MuMessage application as well as any necessary
*          application background processes
* Input(s): N/A
* Output: N/A
************************************************************************************/
void thread_mumessage_start_app(void);

/**************************** END OF COMMON THREADS ********************************/


/******************************** HOST THREADS *************************************/

/***************************** END OF HOST THREADS *********************************/


/******************************* CLIENT THREADS ************************************/

/**************************** END OF CLIENT THREADS ********************************/


/////////////////////////////////END OF THREADS//////////////////////////////////////

#endif      // end of header guard

////////////////////////////////END OF mumessage.h////////////////////////////////////
